name: withyou
description: "WithYou — Student Mental Health Companion"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  lottie: ^2.7.0
  charts_flutter: ^0.12.0

  # Storage / API
  supabase_flutter: ^2.10.0
  shared_preferences: ^2.2.3
  http: ^1.2.2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Add assets here (animations, images, etc.)
  assets:
    - assets/animations/
    - assets/images/
